# ================================================================================
# YOLOv8m Training Configuration for Space Station Safety Detection
# ================================================================================
# Optimized for ≥80% mAP@0.5 accuracy target
# Production-grade hyperparameters for robust performance across challenging scenarios
# ================================================================================

# Model Configuration
# ================================================================================
model:
  architecture: "yolov8m"  # Medium model - balance of speed and accuracy
  pretrained: true          # Use COCO pre-trained weights for transfer learning
  freeze_backbone: false    # Fine-tune all layers for domain adaptation

# Training Hyperparameters
# ================================================================================
training:
  # Core parameters
  epochs: 300                # Extended training for convergence
  batch_size: 16            # Optimized for V100 16GB VRAM (increased from 4)
  image_size: 640           # Standard YOLO input size
  cache_images: true        # Cache images in RAM for faster loading (V100 has enough memory)
  
  # Optimizer settings
  optimizer: "AdamW"        # AdamW for better generalization
  learning_rate: 0.0003     # Increased for faster convergence with larger batch (32)
  weight_decay: 0.0005      # L2 regularization
  momentum: 0.937           # SGD momentum (if using SGD)
  
  # Learning rate schedule
  lr_scheduler: "cosine"    # Cosine annealing with warmup
  warmup_epochs: 3          # Gradual warmup
  warmup_bias_lr: 0.1       # Warmup initial LR for bias
  warmup_momentum: 0.8      # Warmup momentum
  
  # Loss function weights
  box_loss_gain: 7.5        # Bounding box loss weight
  cls_loss_gain: 0.5        # Classification loss weight
  dfl_loss_gain: 1.5        # Distribution focal loss weight
  
  # Multi-scale training
  multi_scale: true         # Train on multiple scales for robustness
  scale_range: [0.5, 1.5]   # Scale variation range
  
  # Mixed precision training
  amp: true                 # Automatic Mixed Precision for faster training
  
  # Early stopping
  patience: 50              # Stop if no improvement for N epochs
  
  # Hardware
  device: "0"               # GPU device ID (use "cpu" for CPU training)
  workers: 8                # Multi-worker data loading for V100 (increased from 0)
  
# Data Augmentation (Optimized for challenging scenarios)
# ================================================================================
augmentation:
  # Spatial augmentations
  hsv_h: 0.015             # HSV-Hue augmentation (±)
  hsv_s: 0.7               # HSV-Saturation augmentation (±)
  hsv_v: 0.4               # HSV-Value (brightness) augmentation - critical for lighting
  
  # Geometric augmentations
  degrees: 10.0            # Rotation (degrees ±)
  translate: 0.1           # Translation (fraction ±)
  scale: 0.5               # Scale variation (gain ±)
  shear: 0.0               # Shear (degrees ±)
  perspective: 0.0         # Perspective distortion
  
  # Flip augmentations
  flipud: 0.0              # Vertical flip probability
  fliplr: 0.5              # Horizontal flip probability
  
  # Advanced augmentations (reduced for memory)
  mosaic: 0.8              # Reduced from 1.0 to 0.8
  mixup: 0.1               # Reduced from 0.15 to 0.1
  copy_paste: 0.05         # Reduced from 0.1 to 0.05
  
  # Lighting augmentations (critical for dark scenarios)
  auto_augment: "randaugment"  # AutoAugment policy
  erasing: 0.4             # Random erasing probability (simulates occlusion)

# Validation Settings
# ================================================================================
validation:
  val_interval: 1          # Validate every N epochs
  save_interval: 10        # Save checkpoint every N epochs
  save_period: -1          # Save checkpoint every N epochs (-1 = only save best)
  
  # Metrics
  iou_threshold: 0.5       # IoU threshold for mAP calculation
  conf_threshold: 0.001    # Confidence threshold for predictions
  nms_iou: 0.7             # NMS IoU threshold
  max_det: 300             # Maximum detections per image
  
  # Validation augmentation
  rect: false              # Rectangular training (faster but less accurate)
  
# Model Checkpointing
# ================================================================================
checkpoint:
  save_best: true          # Save best model based on mAP
  save_last: true          # Save last epoch model
  save_dir: "./models"     # Model save directory
  resume: false            # Resume from last checkpoint
  resume_path: ""          # Path to checkpoint (if resuming)

# Logging and Monitoring
# ================================================================================
logging:
  tensorboard: true        # Enable TensorBoard logging
  log_dir: "./results/runs"
  log_interval: 10         # Log every N batches
  save_plots: true         # Save training plots
  verbose: true            # Verbose output
  
  # Weights & Biases integration (optional)
  wandb: false             # Enable W&B logging
  wandb_project: "space-station-safety-detection"
  wandb_entity: ""         # W&B team name

# Advanced Settings
# ================================================================================
advanced:
  # Label smoothing
  label_smoothing: 0.0     # Label smoothing epsilon
  
  # Class balancing
  cls_weight: null         # Per-class weights (null = auto-calculate)
  
  # Augmentation tuning
  augment_off_epoch: 250   # Turn off heavy augmentation after N epochs
  
  # Model EMA
  ema: true                # Exponential Moving Average of model weights
  ema_decay: 0.9999        # EMA decay rate
  
  # Seed for reproducibility
  seed: 42                 # Random seed
  deterministic: false     # Deterministic mode (slower but reproducible)

# Target Performance Metrics
# ================================================================================
target_metrics:
  map50: 0.80              # Target mAP@0.5 ≥ 80%
  map50_95: 0.60           # Target mAP@0.5:0.95 ≥ 60%
  precision: 0.85          # Target precision ≥ 85%
  recall: 0.80             # Target recall ≥ 80%
  
  # Scenario-specific targets (challenging conditions)
  dark_map50: 0.70         # Dark scenarios ≥ 70% mAP
  vdark_map50: 0.65        # Very dark scenarios ≥ 65% mAP
  clutter_map50: 0.75      # Cluttered scenarios ≥ 75% mAP
